[package]
name = "watermark"
version = {workspace = true}
edition = "2021"
publish = false

[dependencies]
fastedge = { path = "../../" }
urlencoding = "2.1.2"
url = "2.3.1"
image = "0.24.5"
rusty-s3 = "0.5.0"
anyhow = "1.0"

[lib]
crate-type = ["cdylib"]
