[package]
name = "fastedge-derive"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[lib]
name="fastedge_derive"
proc-macro=true
doctest = false

[features]
default = []

[dependencies]
syn = {version = "2.0", features = ["full"]}
quote = "1.0"
proc-macro2 = "1.0"

