[package]
name = "backend"
version = {workspace = true}
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
fastedge = { path = "../../" }
anyhow = "1.0"
querystring = "1.1.0"
urlencoding = "2.1.3"
